# Generated by Django 5.2.5 on 2025-11-18 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nacionalidad',
            old_name='Nacionalidad',
            new_name='nacionalidad',
        ),
    ]
