# Generated by Django 5.2.5 on 2025-11-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_rename_nacionalidad_nacionalidad_nacionalidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nacionalidad',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
